# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LOCC_FE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LOCC_FE
  pod 'Alamofire'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  pod 'Cosmos', '~> 25.0'
  pod "BSImagePicker", "~> 3.1"

  target 'LOCC_FETests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LOCC_FEUITests' do
    # Pods for testing
  end

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
